#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the repeatedString function below.
def repeatedString(s, n):
    a_count = s.count("a") * (n // len(s))
    sub = s[:n % len(s)].count("a")
    return ( a_count+ sub)
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    n = int(input())

    result = repeatedString(s, n)

    fptr.write(str(result) + '\n')

    fptr.close()


Sample Input 0
aba
10
Sample Output 0
7
count of 'a'
