#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter


def sherlockAndAnagrams(s):
    count = 0
    for i in range(1,len(s)+1):
        ana_list = ["".join(sorted(s[j:j+i])) for j in range(len(s)-i+1)]
        ana_count = Counter(ana_list)
        for j in ana_count:
            count+=ana_count[j]*(ana_count[j]-1)//2
    return count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        s = input()

        result = sherlockAndAnagrams(s)

        fptr.write(str(result) + '\n')

    fptr.close()


Sample Input 0
2
abba
abcd
Sample Output 0
4
0
